import { Entity } from "./entity"

export type BaseInteraction = Entity & {
  // type of the interaction
  type: string
  // user content of the interaction
  // for chat, it's the user message
  // for navigate, it's the url
  userContent: string
  // id of the context interaction
  contextId: string | null
  // created at timestamp
  createdAt: number
}

// Chat interaction
// This is a mutable object
export type ChatInteraction = BaseInteraction & ChatInfo & { type: 'chat' }

export type ChatInfo = {
  // model used to generate the content
  model: string
  // content generated by the assistant
  assistantContent: string
  // updated at timestamp
  updatedAt: number
}

// Navigation interaction
// This is a mutable object
export type NavInteraction = BaseInteraction & NavInfo & { type: 'nav' }

export type NavInfo = {
  // title of the page
  title: string
  // description of the page
  description: string | null
  // favicon url of the page
  favIconUrl: string | null
  // image asset id of the page
  imageAssetId: string | null
  // updated at timestamp
  updatedAt: number
}

export type Interaction = ChatInteraction | NavInteraction

// generate the next chat id
export const nextChatId = (interactionId: string | null): string => {
  if (interactionId === null) {
    return ':0'
  }
  const [prefix, indexStr] = interactionId.split(':')
  if (indexStr) {
    const index = parseInt(indexStr)
    const nextIndex = index + 1
    return `${prefix}:${nextIndex}`
  }
  return `${prefix}:0`
}

// generate the previous chat id
export const prevChatId = (interactionId: string | null): string | null => {
  if (interactionId === null) {
    return null
  }
  const [prefix, indexStr] = interactionId.split(':')
  if (indexStr) {
    const index = parseInt(indexStr)
    if (index > 0) {
      const prevIndex = index - 1
      return `${prefix}:${prevIndex}`
    }
  }
  return null
}
